[k3s_master]
master ansible_host=34.234.215.6 ansible_user=ubuntu ansible_ssh_private_key_file=test.pem

[k3s_workers]
worker-ai ansible_host=44.193.213.221 ansible_user=ubuntu ansible_ssh_private_key_file=test.pem node_role=ai
worker-backend ansible_host=44.211.253.76 ansible_user=ubuntu ansible_ssh_private_key_file=test.pem node_role=backend
worker-support ansible_host=44.203.161.187 ansible_user=ubuntu ansible_ssh_private_key_file=test.pem node_role=support

[all:vars]
ansible_python_interpreter=/usr/bin/python3
aws_region=us-east-1
project_name=chat-app

