apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
  labels:
    app: chatflow
data:
  NODE_ENV: "production"
  DB_HOST: "chat-app-postgres.c2z4kg6uw1x8.us-east-1.rds.amazonaws.com"
  S3_BUCKET_NAME: "chat-app-media-6593d98d"
  DB_PORT: "5432"
  DB_NAME: "chatflow"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  MONGO_INITDB_DATABASE: "chatflow"
  JWT_EXPIRY: "15m"
  JWT_REFRESH_EXPIRY: "7d"
  BCRYPT_ROUNDS: "12"
  AWS_REGION: "us-east-1"
  CORS_ORIGIN: "*"
  PROMETHEUS_RETENTION: "15d"
