apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: production
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: production
  labels:
    app: chat-service
spec:
  type: ClusterIP
  selector:
    app: chat-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: production
  labels:
    app: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: production
  labels:
    app: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 3004
      targetPort: 3004
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: production
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: call-service
  namespace: production
  labels:
    app: call-service
spec:
  type: ClusterIP
  selector:
    app: call-service
  ports:
    - name: http
      port: 3005
      targetPort: 3005
      protocol: TCP
---

